# Generated by Django 4.1.6 on 2023-02-13 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='link',
        ),
        migrations.AddField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
