# Generated by Django 4.1.7 on 2023-02-19 13:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_feed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.feed_post_image_url),
        ),
    ]
